{% set name = "open3spn2" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/cabb99/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bbc49f0173d21e9dd873e1ffa425705cc3137de568cee0a0c4c6136c432e060e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - biopython
    - mdtraj
    - nose
    - numpy
    - openmm
    - pandas
    - pdbfixer
    - python
    - scipy

test:
  imports:
    - open3SPN2

about:
  home: https://github.com/cabb99/open3spn2
  summary: 'Implementation of 3SPN2 and 3SPN2.C forcefields in OpenMM'
  description: "An Implementation of the 3SPN.2 and 3SPN.2C coarse-grained molecular model of DNA in OpenMM."
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://open3spn2.readthedocs.io/en/latest/
  dev_url: https://github.com/cabb99/open3spn2

extra:
  recipe-maintainers:
    - cabb99
